{ 
    "internal-error": "Se ha producido un error inesperado. Inténtelo de nuevo."
}